import { createClient } from '@supabase/supabase-js'

// Hardcoded for immediate functionality
const supabaseUrl = 'https://abfnhnuiofdrmergezeu.supabase.co'
const supabaseAnonKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFiZm5obnVpb2Zkcm1lcmdlemV1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjExNTczNTYsImV4cCI6MjA3NjczMzM1Nn0.toON-W6yf49hNfHnwksZsyUr49hAm0xr7XtozdfVooA'
const supabaseServiceKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFiZm5obnVpb2Zkcm1lcmdlemV1Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2MTE1NzM1NiwiZXhwIjoyMDc2NzMzMzU2fQ.ZqtVtBVLzV0-3MCWERWBBCPZTKp6sgs152EU9LEvUYk'

export const supabase = createClient(supabaseUrl, supabaseAnonKey)
export const supabaseAdmin = createClient(supabaseUrl, supabaseServiceKey)
